### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by brhea** [wpilibsuite/vscode-wpilib#50]
VSIX install fails with error log below.

7/25/2018 8:15:16 AM - Microsoft VSIX Installer
7/25/2018 8:15:16 AM - -------------------------------------------
7/25/2018 8:15:16 AM - vsixinstaller.exe version:
7/25/2018 8:15:16 AM - 15.7.105+ga2c5d563c6
7/25/2018 8:15:16 AM - -------------------------------------------
7/25/2018 8:15:16 AM - Command line parameters:
7/25/2018 8:15:16 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\u858680\Downloads\vscode-wpilib-2019.0.0-alpha-4.vsix
7/25/2018 8:15:16 AM - -------------------------------------------
7/25/2018 8:15:16 AM - Microsoft VSIX Installer
7/25/2018 8:15:16 AM - -------------------------------------------
7/25/2018 8:15:17 AM - Initializing Install...
7/25/2018 8:15:17 AM - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__64_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by Kevin-OConnor** [comment]
Are you attempting to install the file from inside VS code as shown in the instructions, or double clicking on it?

**Comment by brhea** [comment]
I double clicked on it.... I just tried to install from VS by using the install from file option and I received the error below:
Unable to install Extension 'wpifirst.vscode-wpilib-2019.0.0-alpha-4' as it is not compatible with Code '1.24.0'.

I also just received an update notice from VS Code that 1.25.1 version is available. Which version are you compatible with?

**Comment by AustinShalit** [comment]
We require 1.25 or later.

**Comment by brhea** [comment]
I upgraded VS Code to 1.25.1 and install worked perfectly with no issues. Thanks.
