### ISSUE TITLE
Failed to create terminal for task wpilib: C++ Build

### ISSUE THREAD

**Issue by Farhan567890** [wpilibsuite/vscode-wpilib#70]
Hi, I'm using Visual Studio Code and have followed every step from https://wpilib.screenstepslive.com/s/currentCS/m/79833/l/932465-creating-a-new-wpilib-project-in-vs-code . When I click on "Yes" to "No "C++ configurations. Yes to refresh". I get an error "Failed to create terminal for task wpilib: C++ Configuration". I'm also getting an include error "#include errors detected. Please update your includePath. IntelliSense features for this translation unit (C:\Users\farha\Desktop\Visual Studio Code FRC-Project\Itrative-Robot\src\main\cpp\Robot.cpp) will be provided by the Tag Parser." . Any way to fix these issues?

**Comment by Farhan567890** [comment]
I get" '.' is not recognized as an internal or external command,operable program or batch file. " I've also attached a picture of what I saw in the terminal.
![untitled](https://user-images.githubusercontent.com/6439835/44967055-ab1be300-af0c-11e8-89df-42faaeb5df38.png)

**Comment by ThadHouse** [comment]
Ok, it's starting cmd not powershell. Try just `gradlew generateVsCode`

**Comment by Farhan567890** [comment]
Ok, now I get
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by ThadHouse** [comment]
Ok. Do you have Java installed on your system? The build system requires it.

**Comment by ThadHouse** [comment]
If you do, you need to make sure you have JAVA_HOME set correctly. 

https://javatutorial.net/set-java-home-windows-10

Here are some instructions how to do this.

**Comment by Farhan567890** [comment]
Ok, it says "build successful" when I enter " gradlew generateVsCode ". Do I have to type this in whenever I build the code? Because when I click on "Build Robot Code" on the top right corner from the more actions tab I get this "Failed to create terminal for task wpilib: C++ Build".
![untitled](https://user-images.githubusercontent.com/6439835/44974360-694f6480-af2d-11e8-9a70-4f32a57d712e.png)

**Comment by ThadHouse** [comment]
Did you restart vs code after fixing those things?

**Comment by Farhan567890** [comment]
Yes

**Comment by ThadHouse** [comment]
That's very odd. I've never seen that error before. What version of VS Code? Also, can you open the developer tools `help -> Toggle Developer Tools` and cause the error to happen again. In the `console` tab of the developer tools see if you can get more information on that error.

**Comment by Farhan567890** [comment]
I'm on Visual Studio Code Version 1.26.1

**Comment by Farhan567890** [comment]
{exception: null, error: Error: Failed to create terminal for task wpilib: C++ Build at e.executeInTerminal (file:///C:/U…, promise: n.C…s.d…e.cancel, handler: undefined, id: 197, …}
error
:
Error: Failed to create terminal for task wpilib: C++ Build at e.executeInTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3058:425) at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:846 at n.Class.define.cancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366) at e.executeCommand (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:820) at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:322 at n.Class.derive._oncancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366) at e.executeTask (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:207) at e.run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3051:14) at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4023:604 at Object.g [as _notify] (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729) at Object.enter (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61) at n.Class.derive._creator._run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902) at n.Class.derive._creator._completed (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343) at <anonymous> at process._tickCallback (internal/process/next_tick.js:188:7)
exception
:
null
handler
:
undefined
id
:
197
parent
:
undefined

**Comment by ThadHouse** [comment]
Is that all thats there, that 1 line? There should be a lot more. Otherwise I'm at a loss of whats happening.

**Comment by Farhan567890** [comment]
INFO no standard startup: panel is active
console.ts:136 [Extension Host] activating extension
console.ts:136 [Extension Host] starting language server
console.ts:136 [Extension Host] Congratulations, your extension "vscode-wpilib" is now active!
notificationsAlerts.ts:41 Failed to create terminal for task wpilib: C++ Build
t.onDidNotificationChange @ notificationsAlerts.ts:41
log.ts:171   ERR File not found: : Error: File not found: 
    at new WindowsPtyAgent (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:25:24)
    at new WindowsTerminal (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:45:24)
    at Object.spawn (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:27:12)
    at new e (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2758:875)
    at e.createProcess (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3327:785)
    at t._createProcess (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3490:488)
    at t (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3475:204)
    at t.create (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:111:339)
    at e._createInstance (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1378:703)
    at e.createInstance (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1377:959)
    at t.createInstance (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3604:899)
    at t [as constructor] (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3589:665)
    at t.create (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:111:339)
    at e._createInstance (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1378:703)
    at e.createInstance (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1377:959)
    at t.createTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3604:216)
    at e.createTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3061:852)
    at e.executeInTerminal.d (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3056:132)
    at new n.Class.derive._oncancel (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:625)
    at e.executeInTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3056:90)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:846
    at n.Class.define.cancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeCommand (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:820)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:322
    at n.Class.derive._oncancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeTask (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:207)
    at e.run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3051:14)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4023:604
    at Object.g [as _notify] (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._creator._run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._creator._completed (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
errors.ts:48 WARNING: Promise with no error callback:165
errors.ts:49 Object
errors.ts:51 Error: File not found: 
    at new WindowsPtyAgent (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:sourcemap:25)
    at new WindowsTerminal (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:sourcemap:45)
    at Object.spawn (C:\Users\farha\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:sourcemap:27)
    at new e (terminalProcess.ts:54)
    at e.createProcess (terminalProcessManager.ts:122)
    at t._createProcess (terminalInstance.ts:715)
    at t (terminalInstance.ts:145)
    at t.create (types.ts:166)
    at e._createInstance (instantiationService.ts:120)
    at e.createInstance (instantiationService.ts:73)
    at t.createInstance (terminalService.ts:99)
    at t [as constructor] (terminalTab.ts:234)
    at t.create (types.ts:166)
    at e._createInstance (instantiationService.ts:120)
    at e.createInstance (instantiationService.ts:73)
    at t.createTerminal (terminalService.ts:75)
    at e.createTerminal (terminalTaskSystem.ts:689)
    at e.executeInTerminal.d (terminalTaskSystem.ts:413)
    at new n.Class.derive._oncancel (winjs.base.js:1662)
    at e.executeInTerminal (terminalTaskSystem.ts:412)
    at terminalTaskSystem.ts:319
    at n.Class.define.cancel.then (winjs.base.js:1587)
    at e.executeCommand (terminalTaskSystem.ts:318)
    at terminalTaskSystem.ts:286
    at n.Class.derive._oncancel.then (winjs.base.js:1587)
    at e.executeTask (terminalTaskSystem.ts:280)
    at e.run (terminalTaskSystem.ts:168)
    at task.contribution.ts:1212
    at Object.g [as _notify] (winjs.base.js:1191)
    at Object.enter (winjs.base.js:867)
    at n.Class.derive._creator._run (winjs.base.js:1089)
    at n.Class.derive._creator._completed (winjs.base.js:1057)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188)
log.ts:171   ERR Failed to create terminal for task wpilib: C++ Build: Error: Failed to create terminal for task wpilib: C++ Build
    at e.executeInTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3058:425)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:846
    at n.Class.define.cancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeCommand (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:820)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:322
    at n.Class.derive._oncancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeTask (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:207)
    at e.run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3051:14)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4023:604
    at Object.g [as _notify] (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._creator._run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._creator._completed (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
errors.ts:48 WARNING: Promise with no error callback:167
errors.ts:49 Objecterror: Error: Failed to create terminal for task wpilib: C++ Build
    at e.executeInTerminal (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3058:425)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:846
    at n.Class.define.cancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeCommand (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:820)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:322
    at n.Class.derive._oncancel.then (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:158:366)
    at e.executeTask (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3053:207)
    at e.run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:3051:14)
    at file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:4023:604
    at Object.g [as _notify] (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:151:729)
    at Object.enter (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:155:61)
    at n.Class.derive._creator._run (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:902)
    at n.Class.derive._creator._completed (file:///C:/Users/farha/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:156:343)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)exception: nullhandler: undefinedid: 167parent: undefinedpromise: n.Class.define.cancel {_value: Error: Failed to create terminal for task wpilib: C++ Build
    at e.executeInTerminal (file:///C:/U…, _isException: false, _errorId: 167}__proto__: Object

**Comment by Farhan567890** [comment]
I that

**Comment by ThadHouse** [comment]
Can you try updating to the newest release of VS Code? I'm at a total loss for this issue, I can't reproduce it locally and I've never seen anyone else reproduce it either.

**Comment by ThadHouse** [comment]
Any updates to this. Through the beta period this has not been reproduced.
